CREATE TABLE board_columns (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    board_id BINARY(16) NOT NULL,
    name VARCHAR(100) NOT NULL,
    position INT NOT NULL,
    is_default BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (board_id) REFERENCES boards(id) ON DELETE CASCADE
);

ALTER TABLE tasks ADD COLUMN position INT DEFAULT 0;
ALTER TABLE tasks ADD COLUMN completed_at TIMESTAMP NULL;
